sudo: false  
language: java    
jdk: oraclejdk8
cache:  
  directories:  
   - $HOME/.m2
   - $HOME/.cache/pip
   - $HOME/conda
   - $HOME/jpm
before_install:
  - if [ ! -e $HOME/conda/bin/activate ]; then
    wget -nc https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh;
    bash Miniconda-latest-Linux-x86_64.sh -f -b -p $HOME/conda;
    fi
  - source $HOME/conda/bin/activate root
  - conda install -y -q -c https://conda.anaconda.org/rdkit rdkit pytables pandas coverage sphinx protobuf
install:
- pip install git+https://github.com/3D-e-Chem/kripodb.git
- mvn package -B
script: xvfb-run mvn verify -B
before_cache:
- wget -nc -O ~/.m2/jpm4j.jar https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar
- java -jar $HOME/.m2/jpm4j.jar -u install com.codacy:codacy-coverage-reporter:assembly
- $HOME/jpm/bin/codacy-coverage-reporter -l Java -r tests/target/jacoco/report/jacoco.xml
